language: python
services: mongodb
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - "sudo apt-get update"
 - "sudo apt-get install python-dev libevent-dev"
install:
  - "sudo pip install -r requirements.txt --use-mirrors"
script:
 - nosetests
